"""Add phase to progress

Revision ID: 4b5d9422c393
Revises: 941ab15da2ec
Create Date: 2025-07-25 16:53:21.652153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5d9422c393'
down_revision = '941ab15da2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('phase')

    # ### end Alembic commands ###
