"""Add progress table

Revision ID: 92da0af724ef
Revises: 1e6f937d9109
Create Date: 2025-07-25 11:37:54.605094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92da0af724ef'
down_revision = '1e6f937d9109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    # ### end Alembic commands ###
